In [32]:
import numpy as np 
from sklearn.datasets import fetch_california_housing
from sklearn import linear_model
from sklearn.cross_validation import train_test_split
from IPython.display import clear_output, Image, display, HTML
import pandas as pd 

dataset = fetch_california_housing(data_home='./')
print("Shape of dataset:", dataset.data.shape)
print("Shape of label:", dataset.target.shape)
# normalized data
dataset.data -= np.mean(dataset.data, axis=0)
dataset.data /= np.std(dataset.data, axis=0)
#X_org, Y_org = dataset.data, dataset.target
df_x=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df_y=pd.DataFrame(dataset.target)


Shape of dataset: (20640, 8)
Shape of label: (20640,)


In [33]:
print( dataset.data[2][0:8])
print( dataset.target[2])


[ 1.7826994   1.85618152  1.15562047 -0.04901636 -0.82077735 -0.02584253
  1.03850269 -1.33282653]
3.521


In [34]:
df_x.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  2.064000e+04  2.064000e+04  2.064000e+04  2.064000e+04  2.064000e+04   
mean   3.734255e-16  8.557001e-16  2.704111e-16 -1.531384e-16 -9.060837e-17   
std    1.000024e+00  1.000024e+00  1.000024e+00  1.000024e+00  1.000024e+00   
min   -1.774299e+00 -2.196180e+00 -1.852319e+00 -1.610768e+00 -1.256123e+00   
25%   -6.881186e-01 -8.453931e-01 -3.994496e-01 -1.911716e-01 -5.638089e-01   
50%   -1.767951e-01  2.864572e-02 -8.078489e-02 -1.010650e-01 -2.291318e-01   
75%    4.593063e-01  6.643103e-01  2.519615e-01  6.015869e-03  2.644949e-01   
max    5.858286e+00  1.856182e+00  5.516324e+01  6.957171e+01  3.025033e+01   

           AveOccup      Latitude     Longitude  
count  2.064000e+04  2.064000e+04  2.064000e+04  
mean   6.064808e-19  1.256263e-15 -6.584553e-15  
std    1.000024e+00  1.000024e+00  1.000024e+00  
min   -2.290000e-01 -1.447568e+00 -2.385992e+00  
25%   -6.171062e-02 -7.967887e-01 -1.113209e+00  
50%   -2.431585e-02 -6.422871e-01  5.389137e-01  
75%    2.037453e-02  9.729566e-01  7.784964e-01  
max    1.194191e+02  2.958068e+00  2.625280e+00

In [35]:
df_y.describe()

0
count  20640.000000
mean       2.068558
std        1.153956
min        0.149990
25%        1.196000
50%        1.797000
75%        2.647250
max        5.000010

In [36]:
reg = linear_model.LinearRegression()

In [37]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [38]:
x_train.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
4520 -1.493529 -0.845393 -0.718489  -0.116883   -0.775742 -0.054062 -0.745288   
29   -1.149173  1.856182 -0.293347  -0.135930   -0.909966 -0.050287  1.033821   
7341 -0.653062  0.028646 -0.781204  -0.196006    1.015973  0.174097 -0.778061   
1067 -0.237697  1.856182 -0.363115  -0.591578   -0.281232  0.791972  1.918693   
5084 -1.298296  1.379433 -0.415270   0.178154   -0.564692  0.002295 -0.773379   

      Longitude  
4520   0.683662  
29    -1.352792  
7341   0.713609  
1067  -1.138166  
5084   0.638740

In [39]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [40]:
reg.coef_

array([[ 0.82937911,  0.11796557, -0.27138395,  0.29658336, -0.00617508,
        -0.03626664, -0.90640968, -0.87851174]])

In [41]:
reg.intercept_

array([ 2.06842327])

In [42]:
print( np.sum(dataset.data[0][0:8]*reg.coef_)+reg.intercept_)

[ 4.13309387]


In [43]:
# predict the house prices.
reg.predict(x_test)

array([[ 2.06302041],
       [ 2.50552547],
       [ 1.61461714],
       ..., 
       [ 1.88260187],
       [ 2.39154106],
       [ 0.30191159]])

In [44]:
#mean square error 
np.mean((reg.predict(x_test) - y_test)**2)

0    0.525009
dtype: float64